name: mypf
description: "Piyush Singh - Personal Portfolio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.17
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/Piyush_Singh_Resume_Updated.pdf